Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/02/2026
Var
   relogio : real
   horas : real
   resto : real
   segundos : real


Inicio
      escreval("digite o tempo: ")
      leia(segundos)
      horas <- segundos div 3600
      resto <- horas mod 3600
      leia(resto



Fimalgoritmo