Algoritmo "tabuada com para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2026
Var
   n, multi, i : inteiro

Inicio

   escreval("Escolha um numero da tabuada")
   leia(n)

   para i de 1 ate 10 faca
      multi <- n * i
      escreval(multi)
   fimpara

Fimalgoritmo